import { GithubUserModel } from "../../ts/interfaces/GithubUserModel";
import { GithubUser } from "../../ts/types/GithubUser";

export const parseGithubUserModel = ({
  avatar_url,
  bio,
  blog,
  company,
  created_at,
  followers,
  followers_url,
  following,
  following_url,
  id,
  location,
  name,
  public_repos,
  repos_url,
  twitter_username,
  url,
  login,
}: GithubUserModel): GithubUser => ({
  avatarUrl: avatar_url,
  bio,
  blog,
  company,
  createdAt: created_at,
  followers,
  followersUrl: followers_url,
  following,
  followingUrl: following_url,
  id,
  location,
  name,
  publicRepos: public_repos,
  reposUrl: repos_url,
  twitterUsername: twitter_username,
  url,
  username: login,
});
